#!/bin/bash
#Creator: Sniffsec
#Description: This is a tool for scan your localnet and find specific ports opened in the ip-s of the localnet


# Colores
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"

# Herramienta
sudo -v

echo
echo -n -e "\e[0;36m\033[1m[*]\033[0m\e[0] Puerto a escanear: "
read -r puerto
echo

direcciones=$(sudo arp-scan --localnet | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')

for ip in $direcciones
	do
		if nc -zvw1 $ip $puerto 2>&1 | grep -q "succeeded"; then
			echo -e "\e[0;36m\033[1m └───>>\033[0m\e[0] El puerto $puerto esta abierto en \e[0;36m\033[1m$ip\033[0m\e[0]"
		fi
	done
